




# get working dates
GET http://localhost:4000/api/workers/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjMzNDg4MTYsImV4cCI6MTY2MzYwODAxNn0.F3Q-NfGlW0JPSusOty9bIu2CnfqShzdO8DY-7XN0s7g





###

GET http://localhost:4000/api/workers/working-dates?workerId=6317b6ded417e4cbffde4da5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjMzNDg4MTYsImV4cCI6MTY2MzYwODAxNn0.F3Q-NfGlW0JPSusOty9bIu2CnfqShzdO8DY-7XN0s7g





###



# get working dates
POST http://localhost:4000/api/appointments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjMzNDg4MTYsImV4cCI6MTY2MzYwODAxNn0.F3Q-NfGlW0JPSusOty9bIu2CnfqShzdO8DY-7XN0s7g

{
    "workingDate":"631cc623d509d93a57af2d19",
    "start_time":"2022-09-20T19:00:00+0300" , 
    "end_time":"2022-09-20T19:30:00+0300" , 
    "worker":"6317b6ded417e4cbffde4da5"    
}


