


# get users
GET http://localhost:4000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs



###

# get user
GET http://localhost:4000/api/users/6324c3f4e28b229425d6c7c6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs


###

# get workers
GET http://localhost:4000/api/workers/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs


###

# get active appointments 
GET http://localhost:4000/api/appointments?isActive=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs




###


# get working date 
GET http://localhost:4000/api/workers/working-dates?workerId=6317b6ded417e4cbffde4da5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs



###



GET http://localhost:4000/api/dashboard/stats HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs




###

GET http://localhost:4000/api/appointments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs






###

# delete appointments
DELETE  http://localhost:4000/api/appointments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs



###

# create appointment
POST http://localhost:4000/api/appointments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs

{
    "workingDate":"631cc623d509d93a57af2d19",
    "start_time":"2022-09-22T12:00:00+0300" , 
    "end_time":"2022-09-22T14:30:00+0300" , 
    "worker":"6317b6ded417e4cbffde4da5"    
}


###

# book for another user appointment
POST http://localhost:4000/api/appointments/book HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs

{
    "service":"Hair Cut",
    "appointmentId":"6328b9272c6cade911e1f7e3" , 
    "userId":"6324c3f4e28b229425d6c7c6" 
    //"userId":"6317b6ded417e4cbffde4da5"
}
//app1 63289a59edb5987a5116ba9b
//app3 63289aa1edb5987a5116baa5

###


# unbook for another user appointment
POST http://localhost:4000/api/appointments/unbook HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs

{
    "appointmentId": "6328b9272c6cade911e1f7e3"
}



###


//'done', 'in-progress', 'didnt-come', 'canceled', 'free', 'hold'
# update appointment status
PATCH  http://localhost:4000/api/appointments/update-status HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE3YjZkZWQ0MTdlNGNiZmZkZTRkYTUiLCJpYXQiOjE2NjM2MTI0ODEsImV4cCI6MTY2Mzg3MTY4MX0.MwoTlxjOJ6Or7IiwEKPo9yPUE8j-mD22ojPPJuzGlYs

{
    "appointmentId": "6328b9272c6cade911e1f7e3",
    "status": "free"
}